unique_name: Product Dimension
object_type: dimension
label: Product Dimension
hierarchies:
  - unique_name: Product Dimension
    label: Product Dimension
    filter_empty: 'yes'
    levels:
      - unique_name: Product Category
      - unique_name: Product Sub-Category
      - unique_name: Product Line
      - unique_name: Product Name
      - unique_name: Product Code
        secondary_attributes:
          - unique_name: Product Code Degen
            label: Product Code
            contains_unique_names: false
            dataset: dimproduct
            is_unique_key: false
            key_columns:
              - productrank
            name_column: productkey
            sort_column: productrank
level_attributes:
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproductcategory
    is_unique_key: false
    key_columns:
      - productcategorykey
    name_column: productcategoryname
  - unique_name: Product Sub-Category
    label: Product Sub-Category
    contains_unique_names: false
    dataset: dimproductsubcategory
    is_unique_key: false
    key_columns:
      - productsubcategorykey
    name_column: productsubcategoryname
  - unique_name: Product Line
    label: Product Line
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product Name
    label: Product Name
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
  - unique_name: Product Code
    label: Product Code
    contains_unique_names: false
    dataset: dimproduct
    is_hidden: true
    is_unique_key: false
    key_columns:
      - productkey
    name_column: productkey
    sort_column: productrank
relationships:
  - from:
      dataset: dimproductsubcategory
      join_columns:
        - productcategorykey
    to:
      level: Product Category
    type: snowflake
  - from:
      dataset: dimproduct
      join_columns:
        - productsubcategorykey
    to:
      level: Product Sub-Category
    type: snowflake
  - from:
      dataset: factinternetsales_ranked_by_product
      join_columns:
        - productkey
    to:
      level: Product Name
    type: snowflake
type: standard
