unique_name: Product
object_type: dimension
label: Product
hierarchies:
  - unique_name: Product Hierarchy
    label: Product
    levels:
      - unique_name: Product Category
      - unique_name: Product Sub-Category
      - unique_name: Product Line
      - unique_name: Product
level_attributes:
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproductcategory
    is_unique_key: false
    key_columns:
      - productcategorykey
    name_column: productcategoryname
  - unique_name: Product Sub-Category
    label: Product Sub-Category
    contains_unique_names: false
    dataset: dimproductsubcategory
    is_unique_key: false
    key_columns:
      - productsubcategorykey
    name_column: productsubcategoryname
  - unique_name: Product Line
    label: Product Line
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product
    label: Product
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
      - productrank
    name_column: englishproductname

relationships:
  - from:
      dataset: dimproduct
      join_columns:
        - productsubcategorykey
    to:
      level: Product Sub-Category
    type: snowflake
  - from:
      dataset: dimproductsubcategory
      join_columns:
        - productcategorykey
    to:
      level: Product Category
    type: snowflake
type: standard
